/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author joaco
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        FlatDarkLaf.setup();
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla
        this.setTitle("FelipeBanco - CLIENTE"); // Pone título
        
        setLocation(100, 50); // Consulta N02 con IA
        setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2_Clientes = new javax.swing.JMenu();
        jMenuItem4_verclientes = new javax.swing.JMenuItem();
        jMenuItem1_verfuncionarios = new javax.swing.JMenuItem();
        jMenuItem5_Sucursales = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_ingresarCliente = new javax.swing.JMenuItem();
        jMenuItem5_ingresarFuncionario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setText("FELIPE BANCO SOFTWARE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jMenu2_Clientes.setText(" Ver");
        jMenu2_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2_ClientesMouseClicked(evt);
            }
        });
        jMenu2_Clientes.addActionListener(this::jMenu2_ClientesActionPerformed);

        jMenuItem4_verclientes.setText("Clientes");
        jMenuItem4_verclientes.addActionListener(this::jMenuItem4_verclientesActionPerformed);
        jMenu2_Clientes.add(jMenuItem4_verclientes);

        jMenuItem1_verfuncionarios.setText("Funcionarios");
        jMenuItem1_verfuncionarios.addActionListener(this::jMenuItem1_verfuncionariosActionPerformed);
        jMenu2_Clientes.add(jMenuItem1_verfuncionarios);

        jMenuItem5_Sucursales.setText("Sucursales");
        jMenu2_Clientes.add(jMenuItem5_Sucursales);

        jMenuBar1.add(jMenu2_Clientes);

        jMenu1.setText("Ingresar");

        jMenuItem1_ingresarCliente.setText("Cliente");
        jMenuItem1_ingresarCliente.addActionListener(this::jMenuItem1_ingresarClienteActionPerformed);
        jMenu1.add(jMenuItem1_ingresarCliente);

        jMenuItem5_ingresarFuncionario.setText("Funcionario");
        jMenuItem5_ingresarFuncionario.addActionListener(this::jMenuItem5_ingresarFuncionarioActionPerformed);
        jMenu1.add(jMenuItem5_ingresarFuncionario);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Préstamos");

        jMenuItem3.setText("Solicitar Préstamo");
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Operaciónes");

        jMenuItem2.setText("Realizar Operación");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4_verclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_verclientesActionPerformed
       VisualizarClientes c = new VisualizarClientes();
    c.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jMenuItem4_verclientesActionPerformed

    private void jMenu2_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2_ClientesActionPerformed
       
    }//GEN-LAST:event_jMenu2_ClientesActionPerformed

    private void jMenu2_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2_ClientesMouseClicked
      
    }//GEN-LAST:event_jMenu2_ClientesMouseClicked

    private void jMenuItem1_ingresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_ingresarClienteActionPerformed
        VentanaNuevoCliente c = new VentanaNuevoCliente();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1_ingresarClienteActionPerformed

    private void jMenuItem5_ingresarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_ingresarFuncionarioActionPerformed
        VentanaNuevoFuncionario c = new VentanaNuevoFuncionario();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5_ingresarFuncionarioActionPerformed

    private void jMenuItem1_verfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_verfuncionariosActionPerformed
        VisualizarFuncionarios c = new VisualizarFuncionarios();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1_verfuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
    } catch (UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error al cargar FlatDarkLaf", ex);
    }

        /* Crear y mostrar la ventana */
    
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2_Clientes;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_ingresarCliente;
    private javax.swing.JMenuItem jMenuItem1_verfuncionarios;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4_verclientes;
    private javax.swing.JMenuItem jMenuItem5_Sucursales;
    private javax.swing.JMenuItem jMenuItem5_ingresarFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
