/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logico.Fachada;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class VentanaNuevoCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaNuevoCliente.class.getName());

    /**
     * Creates new form VentanaNuevoFuncionario
     */
    public VentanaNuevoCliente() {
        FlatDarkLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jButton1aceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2_CI = new javax.swing.JLabel();
        jLabel1_Nombrecompleto = new javax.swing.JLabel();
        jTextField1_nombre = new javax.swing.JTextField();
        jTextField2_CI = new javax.swing.JTextField();
        jLabel3_Pass = new javax.swing.JLabel();
        jPasswordField2_con2 = new javax.swing.JPasswordField();
        jPasswordField1_con1 = new javax.swing.JPasswordField();
        jLabel1_nombre2 = new javax.swing.JLabel();
        jLabel5_FechaNac = new javax.swing.JLabel();
        jTextField4_Dir = new javax.swing.JTextField();
        jLabel7_Tel = new javax.swing.JLabel();
        jLabel6_Dirreción = new javax.swing.JLabel();
        jTextField3_fechanac = new javax.swing.JTextField();
        jTextField5_tel = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("  ");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setName("NuevoFuncionario"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));

        jButton1aceptar.setBackground(new java.awt.Color(255, 255, 255));
        jButton1aceptar.setIcon(new javax.swing.ImageIcon("/home/joaco/Desktop/ITI 2026/Programación Avanzada/FelipeBanco/Cliente/images/next-button.png")); // NOI18N
        jButton1aceptar.setBorder(null);
        jButton1aceptar.addActionListener(this::jButton1aceptarActionPerformed);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2_CI.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_CI.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2_CI.setText("C.I");

        jLabel1_Nombrecompleto.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1_Nombrecompleto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1_Nombrecompleto.setText("Nombre Completo");

        jTextField1_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1_nombre.setForeground(new java.awt.Color(0, 0, 0));

        jTextField2_CI.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2_CI.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3_Pass.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_Pass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3_Pass.setText("Contraseña");

        jPasswordField2_con2.setText("jPasswordField1");

        jPasswordField1_con1.setText("jPasswordField1");

        jLabel1_nombre2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1_nombre2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1_nombre2.setText("Confirmar Contraseña");

        jLabel5_FechaNac.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5_FechaNac.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5_FechaNac.setText("Fecha Nacimiento");

        jTextField4_Dir.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4_Dir.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7_Tel.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7_Tel.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7_Tel.setText("Teléfono");

        jLabel6_Dirreción.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6_Dirreción.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6_Dirreción.setText("Dirección");

        jTextField3_fechanac.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3_fechanac.setForeground(new java.awt.Color(0, 0, 0));

        jTextField5_tel.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5_tel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7_Tel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6_Dirreción)
                            .addGap(89, 89, 89)
                            .addComponent(jTextField4_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5_FechaNac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3_fechanac, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(jPasswordField1_con1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3_Pass, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1_nombre2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPasswordField2_con2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1_Nombrecompleto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2_CI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_Nombrecompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_CI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_Pass)
                    .addComponent(jPasswordField1_con1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2_con2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_nombre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_FechaNac)
                    .addComponent(jTextField3_fechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6_Dirreción)
                    .addComponent(jTextField4_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7_Tel)
                    .addComponent(jTextField5_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton1aceptar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1aceptar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1aceptarActionPerformed
        
        String nombrecompleto = jTextField1_nombre.getText().trim();
        String CI = jTextField2_CI.getText().trim();
        String PSW1 = jPasswordField1_con1.getText().trim();
        String PSW2 = jPasswordField2_con2.getText().trim();
        String FechaNac = jTextField3_fechanac.getText().trim();
        String direccion = jTextField4_Dir.getText().trim();
        String telefono = jTextField5_tel.getText().trim();
        
        // se comprueba que todos los campos NO esten vacios
        if (nombrecompleto.isEmpty() 
                || CI.isEmpty() 
                || PSW1.isEmpty() 
                || PSW2.isEmpty() 
                || FechaNac.isEmpty() 
                || direccion.isEmpty() 
                || telefono.isEmpty()) 
        { 
            JOptionPane.showMessageDialog( rootPane, "Todos los campos son obligatorios." );
            return; 
        }
        
        // Comprobar que las contraseñas coincidan 
        if (!PSW1.equals(PSW2) ) { 
            
            JOptionPane.showMessageDialog( rootPane, "Las contraseñas no coinciden." );
            return; 
        }
        
        // Comprobar y convertir la fecha
        LocalDate fechaNacimiento;
        try { 
            
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
            fechaNacimiento = LocalDate.parse(FechaNac, formato); 
            
        } catch (DateTimeParseException e) { 
            JOptionPane.showMessageDialog( rootPane, "La fecha debe tener el formato dd/MM/yyyy." ); 
            return; 
        }
        
        
       
    }//GEN-LAST:event_jButton1aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaNuevoCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1aceptar;
    private javax.swing.JLabel jLabel1_Nombrecompleto;
    private javax.swing.JLabel jLabel1_nombre2;
    private javax.swing.JLabel jLabel2_CI;
    private javax.swing.JLabel jLabel3_Pass;
    private javax.swing.JLabel jLabel5_FechaNac;
    private javax.swing.JLabel jLabel6_Dirreción;
    private javax.swing.JLabel jLabel7_Tel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1_con1;
    private javax.swing.JPasswordField jPasswordField2_con2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1_nombre;
    private javax.swing.JTextField jTextField2_CI;
    private javax.swing.JTextField jTextField3_fechanac;
    private javax.swing.JTextField jTextField4_Dir;
    private javax.swing.JTextField jTextField5_tel;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
