/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logico.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class VentanaNuevoFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaNuevoFuncionario.class.getName());

    /**
     * Creates new form VentanaNuevoFuncionario
     */
    public VentanaNuevoFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_nombre = new javax.swing.JLabel();
        jLabel2_rol = new javax.swing.JLabel();
        jLabel3_sucursal = new javax.swing.JLabel();
        jTextField1_nombre = new javax.swing.JTextField();
        jComboBox1_rol = new javax.swing.JComboBox<>();
        jButton1aceptar = new javax.swing.JButton();
        jComboBox1_sucursales = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1_nombre.setText("Nombre");

        jLabel2_rol.setText("Rol");

        jLabel3_sucursal.setText("Sucursal");

        jComboBox1_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Servicio", "Esclavo", "Ingeniero", "Supervisor", "Superheroe" }));
        jComboBox1_rol.addActionListener(this::jComboBox1_rolActionPerformed);

        jButton1aceptar.setText("Aceptar");
        jButton1aceptar.addActionListener(this::jButton1aceptarActionPerformed);

        jComboBox1_sucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal Centro", "Sucursal Pocitos", "Sucursal Cordón", " " }));
        jComboBox1_sucursales.addActionListener(this::jComboBox1_sucursalesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3_sucursal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2_rol)
                                .addGap(40, 40, 40)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1_sucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1aceptar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_nombre)
                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3_sucursal)
                    .addComponent(jComboBox1_sucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_rol)
                    .addComponent(jComboBox1_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1aceptar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_rolActionPerformed

    private void jButton1aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1aceptarActionPerformed

        String nombre = jTextField1_nombre.getText();
        String sucursal = jComboBox1_sucursales.getSelectedItem().toString();
        String rol= jComboBox1_rol.getSelectedItem().toString();
        
        JOptionPane.showMessageDialog(rootPane, "Funcionario " + nombre + " ingresado correctamente.");
        jTextField1_nombre.setText("");
        
       
    }//GEN-LAST:event_jButton1aceptarActionPerformed

    private void jComboBox1_sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_sucursalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_sucursalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaNuevoFuncionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1aceptar;
    private javax.swing.JComboBox<String> jComboBox1_rol;
    private javax.swing.JComboBox<String> jComboBox1_sucursales;
    private javax.swing.JLabel jLabel1_nombre;
    private javax.swing.JLabel jLabel2_rol;
    private javax.swing.JLabel jLabel3_sucursal;
    private javax.swing.JTextField jTextField1_nombre;
    // End of variables declaration//GEN-END:variables
}
